<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>jakarta-tutorial</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>session-00-setup</module>
        <module>session-01-jaxrs</module>
        <module>session-02-cdi</module>
        <module>session-03-jpa</module>
        <module>session-04-validation</module>
        <module>session-05-data</module>
        <module>session-06-faces</module>
        <module>session-07-security</module>
        <module>session-08-virtual_threads</module>
        <module>session-09-messaging</module>
        <module>session-10-schedule</module>
        <module>session-11-websockets</module>
        <module>session-12-health</module>
        <module>session-13-batch</module>
        <module>session-14-container</module>
        <module>session-15-payaramicro</module>
    </modules>
</project>
