package com.mycompany.projecttracker.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Persistent project aggregate with its task collection.
 */
@Entity
@Table(name = "PROJECT")
public class Project {

    /** Database identifier generated by the persistence provider. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Human-readable project name. */
    @NotNull
    @Size(min = 3, max = 100)
    @Column(nullable = false, length = 100)
    private String name;

    /** Optional long-form project description. */
    @Size(max = 5000)
    @Lob
    private String description;

    /** Current workflow status for the project. */
    @Column(length = 20)
    private String status;

    /** Planned deadline for the project. */
    private LocalDate deadline;

    /** Audit metadata embedded in the project row. */
    @Embedded
    private AuditInfo auditInfo;

    /**
     * Tasks that belong to this project.
     */
    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true,fetch = FetchType.EAGER)
    private List<Task> tasks = new ArrayList<>();

    /**
     * Creates an empty project for JPA and form binding.
     */
    public Project() {
    }

    /**
     * Adds a task and synchronizes the bidirectional relationship.
     *
     * @param task task to attach to this project
     */
    public void addTask(Task task) {
        /*
         * Se actualizan ambos lados de la relación para que el modelo en memoria coincida con
         * lo que JPA persistirá en la base de datos.
         */
        tasks.add(task);
        task.setProject(this);
    }

    /**
     * Removes a task and clears its project reference.
     *
     * @param task task to detach from this project
     */
    public void removeTask(Task task) {
        /*
         * Al retirar la tarea de la colección se activa orphanRemoval, por lo que JPA puede
         * eliminarla al cerrar la transacción.
         */
        tasks.remove(task);
        task.setProject(null);
    }

    /** @return generated project identifier */
    public Long getId() { return id; }
    /** @param id generated project identifier */
    public void setId(Long id) { this.id = id; }
    /** @return project name */
    public String getName() { return name; }
    /** @param name project name */
    public void setName(String name) { this.name = name; }
    /** @return project description */
    public String getDescription() { return description; }
    /** @param description project description */
    public void setDescription(String description) { this.description = description; }
    /** @return project status */
    public String getStatus() { return status; }
    /** @param status project status */
    public void setStatus(String status) { this.status = status; }
    /** @return project deadline */
    public LocalDate getDeadline() { return deadline; }
    /** @param deadline project deadline */
    public void setDeadline(LocalDate deadline) { this.deadline = deadline; }
    /** @return audit metadata */
    public AuditInfo getAuditInfo() { return auditInfo; }
    /** @param auditInfo audit metadata */
    public void setAuditInfo(AuditInfo auditInfo) { this.auditInfo = auditInfo; }
    /** @return tasks belonging to this project */
    public List<Task> getTasks() { return tasks; }
    /** @param tasks tasks belonging to this project */
    public void setTasks(List<Task> tasks) { this.tasks = tasks; }
}
