package com.mycompany.projecttracker.entity;

import jakarta.persistence.*;

/**
 * Persistent task that belongs to a project.
 */
@Entity
@Table(name = "TASK")
public class Task {

    /** Database identifier generated by the persistence provider. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short task title shown to users. */
    @Column(nullable = false)
    private String title;

    /** Current workflow status for the task. */
    private String status;

    /** Project that owns this task. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROJECT_ID", nullable = false)
    private Project project;

    /** Audit metadata embedded in the task row. */
    @Embedded
    private AuditInfo auditInfo;

    /**
     * Creates an empty task for JPA.
     */
    public Task() {
    }

    /** @return generated task identifier */
    public Long getId() { return id; }
    /** @param id generated task identifier */
    public void setId(Long id) { this.id = id; }
    /** @return task title */
    public String getTitle() { return title; }
    /** @param title task title */
    public void setTitle(String title) { this.title = title; }
    /** @return task status */
    public String getStatus() { return status; }
    /** @param status task status */
    public void setStatus(String status) { this.status = status; }
    /** @return owning project */
    public Project getProject() { return project; }
    /** @param project owning project */
    public void setProject(Project project) { this.project = project; }
    /** @return audit metadata */
    public AuditInfo getAuditInfo() { return auditInfo; }
    /** @param auditInfo audit metadata */
    public void setAuditInfo(AuditInfo auditInfo) { this.auditInfo = auditInfo; }
}
