services:
  db:
    image: postgres:18.3-alpine3.22
    container_name: project_tracker_db
    environment:
      POSTGRES_USER: PROJECT_TRACKER
      POSTGRES_PASSWORD: PROJECT_TRACKER
      POSTGRES_DB: PROJECT_TRACKER
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data in a named volume

volumes:
  db_data: