-- create_users.sql
CREATE TABLE USERS (
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50)
);

CREATE TABLE USER_GROUPS (
    USERNAME VARCHAR(50),
    GROUPNAME VARCHAR(50),
    PRIMARY KEY (USERNAME, GROUPNAME),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

-- Insertar usuarios y roles de ejemplo
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin', 'admin');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('dev', 'dev');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('manager', 'manager');

INSERT INTO USER_GROUPS (USERNAME, GROUPNAME) VALUES ('admin', 'ADMIN');
INSERT INTO USER_GROUPS (USERNAME, GROUPNAME) VALUES ('dev', 'DEVELOPER');
INSERT INTO USER_GROUPS (USERNAME, GROUPNAME) VALUES ('manager', 'MANAGER');
INSERT INTO USER_GROUPS (USERNAME, GROUPNAME) VALUES ('manager', 'DEVELOPER'); -- Un manager también puede ser developer
